// <auto-generated />
using Cafeteria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cafeteria.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230127152700_Criacao-Inicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cafeteria.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("cpfCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Cpf");

                    b.Property<string>("emailCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("emailCliente");

                    b.Property<string>("senhaCliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senhaCliente");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Cafeteria.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("descricaoProduto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricaoProduto");

                    b.Property<string>("nomeProduto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nomeProduto");

                    b.Property<string>("valorProduto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("valorProduto");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
